# Generated by Django 4.1.3 on 2023-01-08 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('img', models.ImageField(height_field=256, upload_to='test', width_field=256)),
            ],
        ),
    ]
