# Generated by Django 4.1.3 on 2023-01-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_dish_id_alter_dish_img_alter_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.recipe'),
        ),
    ]
