# Generated by Django 4.1.3 on 2023-01-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
