# Generated by Django 4.1.3 on 2023-01-16 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_delete_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('date', models.DateField()),
                ('count_of_cooked_dishes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dish')),
            ],
        ),
    ]
