# Generated by Django 4.1.3 on 2023-01-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_dailyreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='count_of_cooked_dishes',
            new_name='count',
        ),
    ]
