# Generated by Django 4.1.3 on 2023-01-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_count_of_cooked_dishes_dailyreport_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
