# Generated by Django 4.1.3 on 2023-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_product_calories_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='count',
            field=models.IntegerField(),
        ),
    ]
